<a href="https://colab.research.google.com/github/adalbertii/LLMs/blob/main/dataset_miejscowosci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd

# Odczytanie pliku CSV
plik_wejsciowy = 'miejscowosci.csv'
df = pd.read_csv(plik_wejsciowy)

# Sprawdzenie, czy istnieje kolumna 'nazwa'
if 'NAZWA' in df.columns:
    # Utworzenie listy niepowtarzalnych miejscowości
    unikalne_miejscowosci = df['NAZWA'].unique()

    # Konwersja do DataFrame
    df_wyniki = pd.DataFrame(unikalne_miejscowosci, columns=['nazwa'])

    # Zapisanie do pliku 'wyniki.csv'
    df_wyniki.to_csv('miejscowosci-distinct.csv', index=False)
    print("Zapisano niepowtarzalne miejscowości do pliku wyniki.csv")
else:
    print("Brak kolumny 'nazwa' w pliku wejściowym.")

Zapisano niepowtarzalne miejscowości do pliku wyniki.csv

In [38]:
df_wyniki[:10]

                   nazwa
0               Adaminów
1                 Adamka
2                 Adamów
3               Adamówka
4                Adamowo
5          Adamowo-Dozin
6               Adolfowo
7            Agnieszkowo
8  Agnieszkowo-Krzyżówki
9            Aleksandrów

In [39]:
df_wyniki.shape

(7604, 1)

In [4]:
!pip install nlpaug

Collecting nlpaug
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (1.26.4)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (2.2.2)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (2.32.3)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from nlpaug) (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown>=4.0.0->nlpaug) (4.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown>=4.0.0->nlpaug) (3.17.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown>=4.0.0->nlpaug) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->nlpaug) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->nlpaug) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->nlpaug) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22.0->nlpaug) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->nlpaug) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown>=4.0.0->nlpaug) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown>=4.0.0->nlpaug) (4.12.2)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown>=4.0.0->nlpaug) (1.7.1)
Downloading nlpaug-1.1.11-py3-none-any.whl (410 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.5/410.5 kB 5.6 MB/s eta 0:00:00
Installing collected packages: nlpaug
Successfully installed nlpaug-1.1.11

In [49]:
import nlpaug.augmenter.char as nac

#aug = nac.KeyboardAug(name='Keyboard_Aug', aug_char_min=1, aug_char_max=1, aug_char_p=0.3, aug_word_p=0.3,
#                      aug_word_min=1, aug_word_max=10, stopwords=None, tokenizer=None, reverse_tokenizer=None,
#                      include_special_char=False, include_numeric=True, include_upper_case=True, lang='en', verbose=0,
#                      stopwords_regex=None, model_path=None, min_char=4)

aug = nac.RandomCharAug(action='substitute', name='RandomChar_Aug', aug_char_min=1, aug_char_max=2, aug_char_p=0.3,
                        aug_word_p=0.3, aug_word_min=1, aug_word_max=10, include_upper_case=True, include_lower_case=True,
                        include_numeric=True, min_char=4, swap_mode='adjacent', spec_char='[!@#$%^&*()_+', stopwords=None,
                        tokenizer=None, reverse_tokenizer=None, verbose=0, stopwords_regex=None)

In [21]:
import csv

In [50]:
with open('miejscowosci-distinct.csv', 'r', newline='') as wej, \
  open('wynik.csv', 'w', newline='') as wyj: # Zmieniono nazwę pliku wynikowego na .csv

  reader = csv.reader(wej)
  writer = csv.writer(wyj, delimiter=':')  # Ustawiamy separator na ':'

  # Odczytujemy nagłówki z pliku wejściowego
  naglowki = next(reader)

  # Dodajemy nagłówek dla nowej kolumny
  #naglowki.append('Nowa nazwa')

  # Zapisujemy nagłówki do pliku wyjściowego
  writer.writerow(naglowki)
  nn = 5
  # Przetwarzamy dane
  for row in reader:
    nazwa = row[0]  # Zakładamy, że nazwa miejscowości jest w pierwszej kolumnie (index 0)

    for _ in range(nn):
      nowa_nazwa = aug.augment(nazwa)
      writer.writerow([nazwa, str(nowa_nazwa[0])])
      #row.append(str(nowa_nazwa[0])) # Dodajemy przetworzoną nazwę do wiersza
      #writer.writerow(row)  # Zapisujemy zmodyfikowany wiersz

In [10]:
 if row:  # Upewniamy się, że wiersz nie jest pusty
                    nazwa_poczatkowa = row[0]  # Zakładamy, że nazwa jest w pierwszej kolumnie
                    for _ in range(n):  # Wykonujemy konwersję n razy
                        nazwa_przetworzona = konwersja(nazwa_poczatkowa)
                        writer.writerow([nazwa_poczatkowa, nazwa_przetworzona])
                        nazwa_poczatkowa = nazwa_przetworzona # kolejna iteracja

In [51]:
dfout = pd.read_csv('wynik.csv')
dfout[:10]

               nazwa
0  Adaminów:edamZnów
1  Adaminów:AZaminUw
2  Adaminów:Ada_inXw
3  Adaminów:^daminó9
4  Adaminów:4damSnów
5      Adamka:AeAmka
6      Adamka:A1amkI
7      Adamka:Ads^ka
8      Adamka:Ad0cka
9      Adamka:AJakka

In [52]:
dfout.shape

(38020, 1)

In [33]:
!pip install datasets
from datasets import load_dataset

Collecting datasets
  Downloading datasets-3.3.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.12)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.3.1-py3-none-any.whl (484 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.9/484.9 kB 8.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.4 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 13.9 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.1 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [34]:
dataset = load_dataset(
    'text',
    data_files='wynik.csv',
    split='train',
)

print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['text'],
    num_rows: 4142
})

In [35]:
dataset_full = dataset.train_test_split(shuffle=True, test_size=0.2)

In [36]:
dataset_train, dataset_valid = dataset_full['train'], dataset_full['test']
print(dataset_train)
print(dataset_valid)

Dataset({
    features: ['text'],
    num_rows: 3313
})
Dataset({
    features: ['text'],
    num_rows: 829
})